import 'package:emart_app/Constant/MyExport.dart';

const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const name = "Name";
const nameHint = "ABC";
const email = "Email";
const emailHint = "abc@gmail.com";
const password = "Password";
const passwordHint = "********";
const reTypepassword = "Re-Type Password";
const forgetpassword = "Forget Password";
const login = "Log in";

const signup = "Sign up";
const createaccount = "or,Create a new account";
const loginwith = "Log in with";
const PrivacyPolicy = "Privacy Policy";
const terms = "Terms & Condidtion";
const aleardy = "Aleardy Have an account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchAnything = "Search Anything",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale ",
    topSeller = "Top Seller",
    brands = "Brands",
    womenDressing = "Women Dresing",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boyGlasses = "Boys Glasses",
    tshirts = "T-Shirts",
    girlsDress = "Girls Dresses",
    topCategories = "Top Categories",
    featuredProduct = "Featured Product",
    featuresCategories = "Feature Categories";
const womenClothing = "Women Dress",
    menClothing = "Men Clothing",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidstoys = "Kids & Toys",
    sports = "Sports",
    jewellery = "Jewellery",
    cellphone = "CellPhone & Tab",
    furtniture = "Furniture";
const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    supportPolicy = "Support Policy";
const productmay = "Product May You Like";
const logout = "Log out";
const wishlist = "My Wishlist", order = "My Order", message = "Message";
const loggedin = "Logged in Successfully";
const loggedout = "Logged out Successfully";
const oldPass = "Old Password", newPass = "New Password";
