// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFggxbaVDe6Q7ZTTWwQ11vnfRW2YNFEE',
    appId: '1:597339092172:web:68f585115b0aacd05efe69',
    messagingSenderId: '597339092172',
    projectId: 'emart-912e2',
    authDomain: 'emart-912e2.firebaseapp.com',
    storageBucket: 'emart-912e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEA19CpggPmvKhF0JuNWCPPCC03qQ-Xg',
    appId: '1:597339092172:android:005cb6cd15e74eca5efe69',
    messagingSenderId: '597339092172',
    projectId: 'emart-912e2',
    storageBucket: 'emart-912e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53CGyj8rS2ATIb6tE7iMGdG7Qxh_Fdz4',
    appId: '1:597339092172:ios:547e287ae5d7845c5efe69',
    messagingSenderId: '597339092172',
    projectId: 'emart-912e2',
    storageBucket: 'emart-912e2.appspot.com',
    iosBundleId: 'com.example.eccomerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC53CGyj8rS2ATIb6tE7iMGdG7Qxh_Fdz4',
    appId: '1:597339092172:ios:32da8cdf1f8d36015efe69',
    messagingSenderId: '597339092172',
    projectId: 'emart-912e2',
    storageBucket: 'emart-912e2.appspot.com',
    iosBundleId: 'com.example.eccomerceapp.RunnerTests',
  );
}
